apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/openpanel
  - resources/pdb.yaml

commonAnnotations:
  environment: prod
  managed-by: kustomize

labels:
  - pairs:
      env: prod
    includeSelectors: false

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: openpanel-api
    path: patches/api-rollout.yaml
  - path: patches/worker.yaml
  - path: patches/configmap.yaml
  - path: patches/ingress.yaml
