singleBinary:
  replicas: 1
  # local-path creates the PV directory on the node where the pod is scheduled.
  persistence:
    storageClass: local-path
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
lokiCanary:
  enabled: false
test:
  enabled: false
