apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero

resources:
  - backup-location.yaml
  - schedule.yaml

labels:
  - pairs:
      project: openpanel-backup
    includeSelectors: false
