server:
  insecure: true

  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.local

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
