apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/openpanel

commonAnnotations:
  environment: staging
  managed-by: kustomize

labels:
  - pairs:
      env: staging
    includeSelectors: false

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: openpanel-api
    path: patches/api-rollout.yaml
  - path: patches/start.yaml
  - path: patches/worker.yaml
  - path: patches/postgres-storage.yaml
  - path: patches/clickhouse-storage.yaml
  - path: patches/redis-storage.yaml
  - path: patches/clickhouse-resources.yaml
  - path: patches/postgres-resources.yaml
  - path: patches/redis-resources.yaml
