
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: openpanel
spec:
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 2Gi
